apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: yolo
spec:
  selector:
    matchLabels:
      app: client
  replicas: 3
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client-container
        image: gcr.io/my-yolo-project-2024/yolomy-client:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000