
- name: Set up and run backend container
  docker_container:
    name: backend
    image: melisaopiyo/yolomy-backend:v1.0.0
    state: started
    restart_policy: always
    ports:
      "5000:5000"
    env:
      MONGODB_URI: "mongodb://mongo:27017/yolo"
    links:
      - mongo